"""End-to-end walkthrough on synthetic data: every step, with its numbers shown.

Run it::

    python demo/walkthrough.py

Each section states what is being computed, prints the intermediate quantities,
and where a ground truth exists, prints that too. The data are generated by
``demo/synthetic.py`` and are not study data; the numbers below are properties
of the estimators, not results.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from aperiodic import config as cfg
from aperiodic import discharges, geometry, preprocess, reporting, scalp, spectral, stats
from demo import synthetic


def rule(title: str) -> None:
    print(f"\n{'=' * 74}\n{title}\n{'=' * 74}")


def line(label: str, value, note: str = "") -> None:
    print(f"  {label:<44} {value}" + (f"   ({note})" if note else ""))


# ═════════════════════════════════════════════════════════════════════════════
def step_1_signal_to_exponent() -> None:
    rule("1. Signal -> power spectrum -> aperiodic exponent")

    truth = 1.50
    raw, sfreq = synthetic.make_recording(exponent=truth, minutes=5.0,
                                          seed=1, n_channels=8)
    line("synthetic ground-truth exponent", f"{truth:.2f}")
    line("recording", f"{raw.shape[0]} channels, "
                      f"{raw.shape[1] / sfreq:.0f} s at {sfreq:.0f} Hz")

    data = preprocess.bandpass(preprocess.average_reference(raw), sfreq)
    line("after average reference and 0.5-45 Hz band-pass", f"{data.shape}")

    epochs = preprocess.epoch(data, sfreq)
    line(f"{cfg.EPOCH_SECONDS:.0f} s epochs", epochs.shape[0])

    rejection = preprocess.reject_adaptive(
        epochs, floor_v=cfg.PTP_FLOOR_V_SCALP)
    line("90th-percentile peak-to-peak",
         f"{rejection.percentile_v * 1e6:.0f} uV")
    line("threshold applied", f"{rejection.threshold_v * 1e6:.0f} uV",
         "the floor wins on a clean recording")
    line("epochs kept", f"{rejection.n_clean} / {rejection.n_created}")

    freqs, psd = spectral.compute_psd(rejection.epochs, sfreq)
    line("PSD", f"{psd.shape[1]} bins, {freqs[0]:.2f}-{freqs[-1]:.2f} Hz",
         f"resolution {freqs[1] - freqs[0]:.2f} Hz")

    fit = spectral.fit_aperiodic(freqs, psd[0])
    ols = spectral.ols_log_log_slope(freqs, psd[0])

    print()
    line("parameterised exponent (specparam)",
         f"{fit.exponent:.3f}   R2 = {fit.r_squared:.3f}",
         f"error vs truth {fit.exponent - truth:+.3f}")
    line("raw log-log slope, no peak model",
         f"{ols.exponent:.3f}   R2 = {ols.r_squared:.3f}",
         f"error vs truth {ols.exponent - truth:+.3f}")
    print("\n  The synthetic spectrum carries a 10 Hz peak. The parameterised fit")
    print("  models it and recovers the background; the raw slope has to run")
    print("  through it. Both are reported in the paper -- the second as the")
    print("  sensitivity analysis showing the SOZ effect survives without peak")
    print("  removal.")


def step_2_artefact_rejection() -> None:
    rule("2. Adaptive rejection: what the floor is for")

    signal, sfreq = synthetic.make_recording(exponent=1.5, minutes=5.0, seed=2)
    clean = preprocess.epoch(signal, sfreq)

    contaminated = clean.copy()
    rng = np.random.default_rng(3)
    hit = rng.choice(contaminated.shape[0], size=6, replace=False)
    contaminated[hit] *= 15.0

    for name, epochs in (("clean recording", clean),
                         ("6 epochs contaminated", contaminated)):
        r = preprocess.reject_adaptive(epochs, floor_v=cfg.PTP_FLOOR_V_SCALP)
        binds = "floor" if r.threshold_v > r.percentile_v else "percentile"
        line(name,
             f"p90 = {r.percentile_v * 1e6:6.0f} uV -> "
             f"threshold {r.threshold_v * 1e6:6.0f} uV, "
             f"rejected {r.n_rejected:2d}/{r.n_created}",
             f"{binds} binds")

    print("\n  A purely relative threshold would always discard the noisiest")
    print("  tenth, including from a recording with nothing wrong with it. The")
    print("  floor stops that. There is no ceiling: a genuinely noisy recording")
    print("  keeps its epochs and is caught by the spectral quality criteria.")


def step_3_discharge_detection() -> None:
    rule("3. Interictal discharges: detection and the two controls")

    truth_rate = 6.0
    # Three contacts of deliberately different amplitude, with discharges on
    # the first only. Amplitude differences of this kind are ordinary
    # intracranially -- impedance, grey versus white matter -- and they are the
    # one situation in which the two threshold families disagree.
    discharging, sfreq = synthetic.make_recording(
        exponent=1.5, minutes=5.0, discharge_rate=truth_rate, seed=4)
    quiet, _ = synthetic.make_recording(
        exponent=1.5, minutes=5.0, seed=6, n_channels=2)
    signal = np.vstack([discharging, quiet * np.array([[3.0], [0.4]])])
    labels = ("discharging", "quiet, x3 amplitude", "quiet, x0.4 amplitude")

    epochs = preprocess.epoch(signal, sfreq)
    line("synthetic discharge rate, contact 1", f"{truth_rate:.1f} / min")
    line("contacts 2 and 3", "no discharges, amplitudes x3 and x0.4")
    line("detector band", f"{cfg.IED_BAND_HZ[0]:.0f}-{cfg.IED_BAND_HZ[1]:.0f} Hz",
         "20 Hz lower edge keeps sleep spindles out")

    print()
    print(f"  {'setting':<10}" + "".join(f"{name:>24}" for name in labels))
    for name, _, _ in discharges.detector_settings():
        rates = discharges.detect(epochs, sfreq, setting=name).rate_per_minute
        print(f"  {name:<10}" + "".join(f"{r:>24.2f}" for r in rates))

    print("\n  Three things to read off this table.")
    print()
    print("  The permissive settings fire on quiet contacts too. A 1/f")
    print("  background is heavy-tailed once band-passed, so a threshold at")
    print("  three times the median is crossed by noise a good fraction of the")
    print("  time. Those settings are not broken and are not discarded; they")
    print("  are in the set so that the control is never read off one operating")
    print("  point.")
    print()
    print("  The two threshold families part company across contacts. A")
    print("  per-channel threshold (neo*) scales itself to each contact, so the")
    print("  x3 and x0.4 contacts come out alike: it has controlled for")
    print("  amplitude, and in doing so has normalised away any genuine")
    print("  difference in how sharp a contact really is -- which is the very")
    print("  thing under test. A shared threshold (neoS*) keeps that difference")
    print("  and reports the quiet contacts far apart; at neoS8 the merely loud")
    print("  one can even outrank the genuinely discharging one, which is")
    print("  amplitude bias in its plainest form.")
    print()
    print("  Neither family is right on its own. They err in opposite")
    print("  directions, both are run, and a conclusion is accepted only if it")
    print("  survives both.")
    print()
    print("  The envelope setting (env5) is neither. Its threshold is refitted")
    print("  in every 5 s window -- the mode of a lognormal fitted to that")
    print("  window -- so it tracks the local background instead of a level set")
    print("  once for the recording. That makes it the most permissive row here")
    print("  on a stationary synthetic background, where there is no drifting")
    print("  background for it to track. It earns its place on real sleep")
    print("  recordings, which do drift, and it is in the set as a check from a")
    print("  different principle rather than as the best-behaved detector.")
    print()
    print("  A note on reading such a table at all: an earlier version of this")
    print("  package thresholded the envelope at a multiple of the recording's")
    print("  median instead. That produced a far tidier row -- about 5 per")
    print("  minute with discharges, zero without -- and was simply not the")
    print("  published detector. Looking reasonable is not evidence of being")
    print("  right.")

    # For the re-estimation the setting has to leave enough epochs standing.
    setting = next(
        (name for name, _, _ in reversed(discharges.detector_settings())
         if discharges.detect(epochs, sfreq, setting=name)
         .discharge_free_mask()[0].sum() >= cfg.MIN_DISCHARGE_FREE_EPOCHS),
        None)
    if setting is None:
        print("\n  No setting leaves "
              f"{cfg.MIN_DISCHARGE_FREE_EPOCHS} discharge-free epochs; the "
              "re-estimation is skipped, exactly as it is for a contact that "
              "discharges too often.")
        return

    print(f"\n  Re-estimating on setting {setting}, the most conservative one "
          f"leaving\n  at least {cfg.MIN_DISCHARGE_FREE_EPOCHS} epochs:")
    detection = discharges.detect(epochs, sfreq, setting=setting)
    keep = detection.discharge_free_mask()[0]
    matched = discharges.matched_random_subset(keep, np.random.default_rng(5))

    freqs, psd_all = spectral.compute_psd(epochs, sfreq)
    _, psd_free = spectral.compute_psd(epochs[keep], sfreq)
    _, psd_matched = spectral.compute_psd(epochs[matched], sfreq)

    print()
    line("exponent, all epochs",
         f"{spectral.fit_aperiodic(freqs, psd_all[0]).exponent:.3f}",
         f"n = {epochs.shape[0]}")
    line("exponent, discharge-free epochs only",
         f"{spectral.fit_aperiodic(freqs, psd_free[0]).exponent:.3f}",
         f"n = {int(keep.sum())}")
    line("exponent, equally sized random subset",
         f"{spectral.fit_aperiodic(freqs, psd_matched[0]).exponent:.3f}",
         f"n = {int(matched.sum())}")
    print("\n  The third row is the one that makes the second interpretable.")
    print("  Dropping discharges also drops epochs, and fewer epochs alone move")
    print("  a spectral estimate. Matching the count separates the two.")


def step_4_geometry() -> None:
    rule("4. Contact labels and along-electrode distance")

    # Invented labels showing the shapes the parser has to cope with: vendor
    # prefixes, reference suffixes, the apostrophe that marks a counterpart
    # shaft, simultaneous scalp channels, and physiological channels.
    examples = (
        "POL B'12",
        "EEG A1-REF",
        "SEEG C7",
        "Fz",
        "ECG",
    )
    for label in examples:
        parsed = geometry.parse_contact_label(label)
        line(f"parse {label!r}", parsed if parsed else "not a brain contact")

    electrode = geometry.Electrode(
        name="A", soz_contacts=frozenset({5, 6}),
        ablated_contacts=frozenset({5, 6}),
        target_structure="right anterior hippocampus")
    print()
    line("SOZ contacts", sorted(electrode.soz_contacts))
    line("SOZ centre (mean contact number)", f"{electrode.soz_center:.1f}")
    line("target structure", electrode.target_structure)
    line("region by the keyword rule", electrode.region())
    print()
    for contact in (1, 5, 9, 12, 20):
        distance = electrode.distance_mm(contact)
        beyond = " -- beyond the 63 mm cap" if distance > cfg.MAX_DISTANCE_MM else ""
        line(f"contact {contact:2d}", f"{distance:5.1f} mm from SOZ centre" + beyond)


def step_5_intracranial_statistics(contacts: pd.DataFrame) -> None:
    rule("5. Intracranial: SOZ contrast and the distance gradient")

    line("synthetic cohort",
         f"{contacts.Subject.nunique()} patients, {len(contacts)} contacts, "
         f"{contacts.Electrode.nunique()} electrodes")
    line("ground truth written into the data",
         f"SOZ {synthetic.SOZ_DEPRESSION:+.2f}, "
         f"recovering over {synthetic.GRADIENT_RECOVERY_MM:.0f} mm")

    model = stats.soz_contrast_model(contacts)
    coefficient = model.params["Is_SOZ"]
    ci = model.conf_int().loc["Is_SOZ"]
    print()
    print("  Exponent ~ Is_SOZ + (1 | Subject)")
    line("SOZ coefficient",
         f"{coefficient:+.3f}  {reporting.format_ci(ci[0], ci[1])}",
         reporting.format_p(model.pvalues['Is_SOZ']))

    gradient_set = contacts.dropna(subset=["Distance_mm"])
    gradient_set = gradient_set[gradient_set.Distance_mm <= cfg.MAX_DISTANCE_MM]
    gradient = stats.distance_gradient_model(gradient_set)
    slope = gradient.params["Distance_mm"]
    gci = gradient.conf_int().loc["Distance_mm"]
    print()
    print("  Exponent ~ Distance_mm + (1 | Subject / Electrode)")
    line("contacts in the gradient set", len(gradient_set))
    line("slope per mm",
         f"{slope:+.5f}  {reporting.format_ci(gci[0], gci[1], 5)}",
         reporting.format_p(gradient.pvalues['Distance_mm']))

    with_covariate = stats.distance_gradient_model(
        gradient_set, covariates=("Discharge_rate",))
    adjusted = with_covariate.params["Distance_mm"]
    print()
    print("  ... the same model with discharge rate as a covariate:")
    line("slope per mm, discharge-adjusted",
         f"{adjusted:+.5f}",
         f"{100 * (adjusted - slope) / abs(slope):+.1f}% vs unadjusted")
    line("discharge-rate coefficient",
         f"{with_covariate.params['Discharge_rate']:+.5f}")


def step_6_trajectory_control(contacts: pd.DataFrame) -> None:
    rule("6. Does the gradient belong to SOZ trajectories, or to depth electrodes?")

    slopes = stats.per_electrode_slopes(contacts)
    line("electrodes with a slope estimate",
         f"{len(slopes)}  "
         f"({int(slopes.Contains_SOZ.sum())} SOZ-bearing, "
         f"{int((~slopes.Contains_SOZ).sum())} SOZ-free)",
         f"needs >= {cfg.MIN_CONTACTS_FOR_SLOPE} contacts")

    comparison = stats.compare_trajectory_classes(slopes)
    print()
    line("SOZ-bearing, mean slope per patient",
         f"{comparison['soz_mean']:+.5f} / mm",
         f"vs 0: {reporting.format_p(comparison['soz_vs_zero_p'])}")
    line("SOZ-free, mean slope per patient",
         f"{comparison['non_soz_mean']:+.5f} / mm",
         f"vs 0: {reporting.format_p(comparison['non_soz_vs_zero_p'])}")
    line("paired difference",
         f"t = {comparison['paired_t']:.2f}, n = {comparison['n_paired']}",
         reporting.format_p(comparison['paired_p']))

    print("\n  Both classes are regressed on position along the electrode's own")
    print("  shaft, because a SOZ-free electrode has no SOZ centre to measure")
    print("  from. Slopes are averaged within patient before the comparison, so")
    print("  that a patient with more electrodes does not outvote one with few.")


def step_7_scalp(scalp_table: pd.DataFrame) -> None:
    rule("7. Scalp: lesion-locked frame, regions, classes, change")

    subject = scalp_table.Subject.iloc[0]
    one = scalp_table[scalp_table.Subject == subject]
    side = one.Lesion_side.iloc[0]
    pre_raw = dict(zip(one.Channel, one.Pre))
    post_raw = dict(zip(one.Channel, one.Post))

    line("example patient", f"{subject}, lesion side {side}")
    pre = scalp.mirror_to_lesion_frame(pre_raw, side)
    post = scalp.mirror_to_lesion_frame(post_raw, side)
    if side.lower().startswith("l"):
        line("mirror-flipped", "C3 <-> C4, F7 <-> F8, ... ; midline unchanged")
    else:
        line("mirror-flipped", "no -- already in the lesion frame")

    print()
    for name, channels in scalp.region_channels().items():
        line(f"{name} ({len(channels)} channels)",
             f"pre {scalp.region_mean(pre, channels):.3f} -> "
             f"post {scalp.region_mean(post, channels):.3f}   "
             f"delta {scalp.delta(pre, post, channels):+.3f}")
    line("whole scalp (19 channels)",
         f"pre {scalp.whole_scalp(pre):.3f} -> post {scalp.whole_scalp(post):.3f}")

    classes = scalp.channel_classes("MedialTemporal", side)
    print()
    line("midline class", list(classes.midline))
    line("region-mapped class (MedialTemporal)", list(classes.region_mapped))
    line("non-corresponding class",
         f"{len(classes.non_corresponding)} channels")
    line("midline / region-mapped overlap",
         list(classes.overlap) or "none for this region")
    line("SCI = dMidline - dNon-corresponding",
         f"{scalp.selective_contrast_index(pre, post, classes):+.3f}")

    rule("7b. Regional change across the cohort, FDR-corrected")
    wide = scalp_table.pivot_table(index=["Subject", "Outcome"],
                                   columns="Channel",
                                   values=["Pre", "Post"])
    from scipy import stats as st

    labels, pvalues, means = [], [], []
    for name, channels in scalp.region_channels().items():
        deltas = np.array([
            np.mean([wide.loc[idx, ("Post", c)] - wide.loc[idx, ("Pre", c)]
                     for c in channels])
            for idx in wide.index])
        labels.append(name)
        means.append(float(deltas.mean()))
        pvalues.append(float(st.ttest_1samp(deltas, 0.0).pvalue))

    _, adjusted = stats.fdr(pvalues)
    print()
    for label, mean, raw, adj in zip(labels, means, pvalues, adjusted):
        line(f"delta {label}", f"{mean:+.4f}",
             f"{reporting.format_p(raw)}  ->  FDR {reporting.format_p(adj)}")


def step_8_outcome(scalp_table: pd.DataFrame) -> None:
    rule("8. Outcome: paired change, ANCOVA, permutation, cross-modal correlation")

    per_subject = (scalp_table.groupby(["Subject", "Outcome"])
                   .agg(Pre=("Pre", "mean"), Post=("Post", "mean"),
                        Contrast=("Contrast", "first"))
                   .reset_index())
    midline = (scalp_table[scalp_table.Channel.isin(cfg.MIDLINE_CHANNELS)]
               .groupby("Subject")
               .agg(Pre_mid=("Pre", "mean"), Post_mid=("Post", "mean"))
               .reset_index())
    per_subject = per_subject.merge(midline, on="Subject")
    per_subject["Delta_mid"] = per_subject.Post_mid - per_subject.Pre_mid

    for group in ("Good", "Poor"):
        rows = per_subject[per_subject.Outcome == group]
        result = stats.paired_change(rows.Pre_mid, rows.Post_mid)
        line(f"{group} (n = {result.n}), midline pre -> post",
             f"{result.mean_change:+.4f}   d = {result.d:+.2f} "
             f"{reporting.format_ci(*result.d_ci)}",
             reporting.format_p(result.p))
        line("   sensitivity and null evidence",
             f"Wilcoxon {reporting.format_p(result.wilcoxon_p)}, "
             f"BF01 = {result.bf01:.3g}")

    print("\n  BF01 is the evidence *for* no change. A non-significant p value")
    print("  cannot support a null claim; a Bayes factor can distinguish")
    print("  evidence of absence from absence of evidence.")

    print()
    ancova = stats.ancova_outcome(per_subject, dependent="Post",
                                  covariate="Pre", group="Outcome",
                                  n_permutations=2000)
    print("  Post ~ Pre + C(Outcome)")
    line("outcome coefficient", f"{ancova.coefficient:+.4f}",
         reporting.format_p(ancova.p))
    line("partial eta squared", f"{ancova.partial_eta_squared:.3f}")
    line("permutation p (2,000 label shuffles)",
         reporting.format_p(ancova.permutation_p),
         "asymptotic assumptions are not comfortable at n = 16")

    print()
    correlation = stats.spearman_bootstrap(per_subject.Contrast,
                                           per_subject.Delta_mid,
                                           n_boot=2000)
    line("intracranial contrast vs midline change",
         f"rho = {correlation.rho:+.2f} "
         f"{reporting.format_ci(correlation.ci_low, correlation.ci_high)}",
         f"n = {correlation.n}, {reporting.format_p(correlation.p)}")

    partial = stats.partial_spearman(per_subject.Contrast,
                                     per_subject.Delta_mid,
                                     per_subject.Pre_mid)
    line("... adjusting for the pre-operative level",
         f"rho = {partial.rho:+.2f} "
         f"{reporting.format_ci(partial.ci_low, partial.ci_high)}",
         reporting.format_p(partial.p))


def step_9_reporting() -> None:
    rule("9. How a p value is rendered")

    for value in (0.4, 0.034514, 0.0245, 0.049, 0.051, 0.0032, 0.000654):
        line(f"p = {value:<10.6g}", reporting.format_p(value))

    print("\n  0.049 and 0.051 keep three decimals. Under the plain rule both")
    print("  would print as 0.05, and a result either side of the conventional")
    print("  threshold would look identical on the page.")

    print()
    raw = 0.034514
    correct = reporting.round_p(raw)
    # The trap: the value reaches the page at three decimals first -- from an
    # earlier draft, a figure label, a table -- and the two-decimal rule is
    # then applied to that printed string rather than to the analysis output.
    intermediate = f"{raw:.3f}"
    wrong = reporting.round_p(float(intermediate))

    line("analysis value", f"{raw}")
    line("rounded once, from the value", correct, "correct")
    line("shown at three decimals first", intermediate)
    line("...then the rule applied to that", wrong,
         "wrong -- rounding twice is not rounding once")
    print("\n  0.03 and 0.04 are different numbers, and the second one never")
    print("  existed in the analysis. This is why the rule is a function of the")
    print("  value the analysis produced, and not something applied to a number")
    print("  already on the page.")


def main() -> None:
    print(__doc__)
    step_1_signal_to_exponent()
    step_2_artefact_rejection()
    step_3_discharge_detection()
    step_4_geometry()

    contacts = synthetic.make_contact_table()
    scalp_table = synthetic.make_scalp_table(contacts)

    step_5_intracranial_statistics(contacts)
    step_6_trajectory_control(contacts)
    step_7_scalp(scalp_table)
    step_8_outcome(scalp_table)
    step_9_reporting()

    rule("Done")
    print("  Every number above came from synthetic data with a known ground")
    print("  truth. Nothing here is a study result.")


if __name__ == "__main__":
    main()
